// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var MyDep$Step7 = require("./myDep.bs.js");

var secret = MyDep$Step7.secret + " world";

exports.secret = secret;
/* No side effect */
