// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");
var MyDep$Step7 = require("./myDep.bs.js");
var MyDep2$Step7 = require("./myDep2.bs.js");

console.log(MyDep$Step7.secret);

console.log(MyDep2$Step7.secret);

Random.self_init(/* () */0);

Random.$$int(2) === 0;

Random.self_init(/* () */0);

var match = Random.$$int(2) === 0;

var msg = match ? null : "This message might not display.";

if (msg !== null) {
  console.log(msg);
}

setTimeout((function (param) {
        console.log("Here's a message after a 1 second timeout.");
        return /* () */0;
      }), 1000);

exports.msg = msg;
/*  Not a pure module */
